version: '3.5'

volumes:
  nextcloud:
  mariadb:

services:
  mariadb:
    image: mariadb
    restart: always
    volumes:
      - mariadb:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud

  nextcloud:
    build: ./nextcloud
    ports:
      - 8080:80
    links:
      - mariadb
    volumes:
      - nextcloud:/var/www/html
    restart: always
    environment:
      - NEXTCLOUD_TRUSTED_DOMAINS=${HOST}
      - VIRTUAL_HOST=${HOST}
      - VIRTUAL_PORT=8080
      - LETSENCRYPT_HOST=${HOST}
      - LETSENCRYPT_EMAIL=${EMAIL}

networks:
  default:
    external:
      name: proxy